#!/bin/bash

#引数
##一つ目必須，texファイル名
##二つ目任意，bibファイル名

if [ -z $1 ];then
  read -p "texファイルの名前を入力してください:" file
    if [ !  -f  $file ];then
      echo "そのファイルは存在しません"
      exit 1
    fi
  set $file
fi

echo "check {encode}"
enc=`nkf -g $1`

if [ ${enc} = 'UTF-8' ];then
   encode='utf8'
elif [ ${enc} = 'Shift_JIS' ];then
   encode='sjis'
elif [ ${enc} = 'EUC-JP' ];then
   encode='enc' 
elif [ ${enc} = 'ISO-2022-JP' ];then
   encode='jis'
else 
    echo "文字コード" + ${enc} + "には対応していません"
    exit 1
fi
echo $1 + "'s encode is " + ${encode}

echo "--------1st platex--------"
platex -kanji=${encode} $1

#二つ目の引数ある場合はpbibする
if [ ! -z $2 ];then
    echo "--------pbibtex--------"
    platex -kanji=${encode} $1
    echo "--------re platex--------"
    platex -kanji=${encode} $1
fi

echo "--------2nd platex--------"
platex -kanji=${encode} $1
echo "---------dvipdfmx---------"
dvipdfmx ${1%.tex}
echo "---------open pdf---------"
open ${1%.tex}.pdf
